name: Custom Action Workflows

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v3     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: zivamram
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  
      - name: Docker Pull
        run: docker pull zivamram/custom-action:latest
      - name: Docker Run
        run: docker run -p 5000:5000 zivamram/custom-action:latest
      - name: docker push
        run: |
          docker tag zivamram/custom-action:latest zivamram/custom-action:${{ github.run_id }}
          docker push zivamram/custom-action:${{ github.run_id }}
      - name: Send Slack notification on failure
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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